openapi: 3.1.0

info:
  title: Mock API for the example UI screen design 
  version: 1.0.0
  description: |
    REST API for managing the customer management screen in Store Management system

    Supported resources:

    * Customers
    * Companys
    * Users


  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0

servers:
  - url: http://localhost:8080/api/v1
    description: Local development server

tags:
  - name: Customers
    description: Customer metadata operations

  - name: Users
    description: User metadata operations

paths:

  # =========================================================
  # Database
  # =========================================================

  /customers/metrics:
    get: 
      tags: 
        - Customers
      summary: Get metrics dashboard
      operationId: getCustomerMetrics
      responses: 
        '200':
          description: Get general metrics successfully
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerMetricsResponse'
              example:
                status: success,
                data: 
                  total_customers: 
                    value: 8468,
                    change_percentage: 20.0
                    trend: up
                  members: 
                    value: 1210
                    change_percentage: 15.0
                    trend: up
                  active_now:
                    value: 316,
                    recent_active_users: 
                      - id: "usr_101"
                        name: "Olivia"
                        avatar_url: "https://images.unsplash.com/photo-15252532-23235586-bec356"
                      - id: "usr_102"
                        name: Phoenix"
                        avatar_url: "https://images.unsplash.com/photo-132as1das546-112dsd3s55"
                      - id: "usr_103"
                        name: "Lana"
                        avatar_url: "https://images.unsplash.com/photo-12312321ece-1212321d3ed"
                      - id: "usr_104"
                        name: "Demi"
                        avatar_url: "https://images.unsplash.com/photo-212312321c3e-83832329832d"
                      - id: "usr_105"
                        name: "Candice"
                        avatar_url: "https://images/unsplash.com/photo-21312312ce-21e21da32323"

  /customers:
    get: 
      tags:
        - Customers
      summary: Get customer list (pagination, searching, arrange)
      operationId: getCustomerList
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: Integer
            default: 1
          example: 1
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 7
          example: 7
        - name: search
          in: query
          required: false
          schema: 
            type: string
          example: "Framer"
        - name: sort_by
          in: query
          required: false
          schema:   
            type: string
            enum: [company_name,status, created_at]
            default: company_name
        - name: order
          in: query
          required: false
          schema: 
            type: string
            enum: [asc, desc]
            default: asc

      responses: 
        '200': 
          description: Get customer list
          content: 
            application/json:
              schema: 
                $ref: "#/compoents/schemas/CustomerListResponse"
              example:
                status: success
                data:
                  - id: "cust_01"
                    company:
                      name: "Framer"
                      domain: "framer.com"
                      logo_url: "https://logo.clearbit.com/framer.com"
                    status: Customer
                    about: 
                      category: "Desing tools"
                      description: "make beautiful website in mininutes."
                    users:
                      total_count: 9
                      preview:
                        - id: "u_f1"
                          name: "Alex"
                          avatar_url: "https://i.pavatar.cc/150?u=f1"
                        - id: "u_f2"
                          name: "Ben"
                          avatar_url: "https://i.pavatar.cc/150?u=f2"
                        - id: "u_f3"
                          name: "Clara"
                          avatar_url: "https://i.pravatar.cc/150?u=f3"
                        - id: "u_f4"
                          name: "Dan"
                          avatar_url: "https://i.pravatar.cc/150?u=f4"
                        - id: "u_f5"
                          name: "Eva"
                          avatar_url: "https://i.pravatar.cc/150?u=f5"
                      remaining_count: 4
                  - id: "cust_02"
                    company:
                      name: "Intercom"
                      domain: "intercom.com"
                      logo_url: "https://logo.clearbit.com/intercom.com"
                    status: Customer
                    about: 
                      category: "Customer Engagement"
                      description: "Build lasting customer relationships with Intercom"
                    users:
                      total_count: 7
                      preview:
                        - id: "u_i1"
                          name: "Frank"
                          avatar_url: "https://i.pavatar.cc/150?u=i1"
                        - id: "u_i2"
                          name: "Grace"
                          avatar_url: "https://i.pavatar.cc/150?u=i2"
                        - id: "u_i3"
                          name: "Hannah"
                          avatar_url: "https://i.pravatar.cc/150?u=i3"
                        - id: "u_i4"
                          name: "Ian"
                          avatar_url: "https://i.pravatar.cc/150?u=i4"
                        - id: "u_i5"
                          name: "Jack"
                          avatar_url: "https://i.pravatar.cc/150?u=i5"
                      remaining_count: 2       
                  - id: "cust_03"
                    company:
                      name: "Figma"
                      domain: "figma.com"
                      logo_url: "https://logo.clearbit.com/figma.com"
                    status: Customer
                    about: 
                      category: "Design Tools"
                      description: "The collaborative interface design tool."
                    users:
                      total_count: 11
                      preview:
                        - id: "u_fg1"
                          name: "Kate"
                          avatar_url: "https://i.pavatar.cc/150?u=fg1"
                        - id: "u_fg2"
                          name: "Leo"
                          avatar_url: "https://i.pavatar.cc/150?u=fg2"
                        - id: "u_fg3"
                          name: "Mia"
                          avatar_url: "https://i.pravatar.cc/150?u=fg3"
                        - id: "u_fg4"
                          name: "Noah"
                          avatar_url: "https://i.pravatar.cc/150?u=fg4"
                        - id: "u_fg5"
                          name: "Olivia"
                          avatar_url: "https://i.pravatar.cc/150?u=fg5"
                      remaining_count: 6
                  - id: "cust_04"
                    company:
                      name: "Linear"
                      domain: "linear.com"
                      logo_url: "https://logo.clearbit.com/linear.com"
                    status: Customer
                    about: 
                      category: "Developer Tools"
                      description: "the issue tracking tool you'll enjoy using."
                    users:
                      total_count: 8
                      preview:
                        - id: "u_l1"
                          name: "Peter"
                          avatar_url: "https://i.pavatar.cc/150?u=l1"
                        - id: "u_l2"
                          name: "Quin"
                          avatar_url: "https://i.pavatar.cc/150?u=l2"
                        - id: "u_l3"
                          name: "Rose"
                          avatar_url: "https://i.pravatar.cc/150?u=l3"
                      remaining_count: 5
                  - id: "cust_05"
                    company:
                      name: "Basecamp"
                      domain: "basecamp.com"
                      logo_url: "https://logo.clearbit.com/basecamp.com"
                    status: Churned
                    about: 
                      category: "Project Management"
                      description: "Project management and team communication"
                    users:
                      total_count: 6
                      preview:
                        - id: "u_b1"
                          name: "Sam"
                          avatar_url: "https://i.pavatar.cc/150?u=b1"
                        - id: "u_b2"
                          name: "Tina"
                          avatar_url: "https://i.pavatar.cc/150?u=b2"
                        - id: "u_b3"
                          name: "Ulysses"
                          avatar_url: "https://i.pravatar.cc/150?u=b3"
                        - id: "u_b4"
                          name: "Vicky"
                          avatar_url: "https://i.pravatar.cc/150?u=b4"
                        - id: "u_b5"
                          name: "Will"
                          avatar_url: "https://i.pravatar.cc/150?u=b5"
                      remaining_count: 1
                  - id: "cust_06"
                    company:
                      name: "Stripe"
                      domain: "stripe.com"
                      logo_url: "https://logo.clearbit.com/strip.com"
                    status: Churned
                    about: 
                      category: "Financial Tools"
                      description: "Payment processing platform for the internet"
                    users:
                      total_count: 13
                      preview:
                        - id: "u_s1"
                          name: "Xavier"
                          avatar_url: "https://i.pavatar.cc/150?u=s1"
                        - id: "u_s2"
                          name: "Yara"
                          avatar_url: "https://i.pavatar.cc/150?u=s2"
                        - id: "u_b3"
                          name: "Zack"
                          avatar_url: "https://i.pravatar.cc/150?u=s3"
                        - id: "u_b4"
                          name: "Alice"
                          avatar_url: "https://i.pravatar.cc/150?u=s4"
                        - id: "u_b5"
                          name: "Bob"
                          avatar_url: "https://i.pravatar.cc/150?u=s5"
                      remaining_count: 8
                  - id: "cust_07"
                    company:
                      name: "Webflow"
                      domain: "webflow.com"
                      logo_url: "https://logo.clearbit.com/webflow.com"
                    status: Customer
                    about: 
                      category: "Web development"
                      description: "Create a custom website + no-code website builder"
                    users:
                      total_count: 7
                      preview:
                        - id: "u_w1"
                          name: "Xavier"
                          avatar_url: "https://i.pavatar.cc/150?u=w1"
                        - id: "u_w2"
                          name: "Yara"
                          avatar_url: "https://i.pavatar.cc/150?u=w2"
                        - id: "u_w3"
                          name: "Zack"
                          avatar_url: "https://i.pravatar.cc/150?u=w3"
                        - id: "u_w4"
                          name: "Alice"
                          avatar_url: "https://i.pravatar.cc/150?u=w4"
                        - id: "u_w5"
                          name: "Bob"
                          avatar_url: "https://i.pravatar.cc/150?u=w5"
                      remaining_count: 2
                pagination: 
                  current_page: 1
                  per_page: 7
                  total_records: 8486
                  total_pages: 184
                  has_next: true
                  has_previous: false
                    
    post:
      summary: Add new customer
      operationId: createCustomer
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              $ref:'#/components/schemas/CreateCustomerRequest'
            example:
              company_name: "Linear"
              domain: "linear.app"
              category: "Developer Tools"
              description: "The issue tracking tool you'll enjoy using."
      responses:
        '201': 
          desciption: Create new customer successfully
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/CustomerItem"
  
  /customers/export:
    get:
      summary: "Export customer list"
      operationId: exportCustomers
      parameters:
        - name: format
          in: query
          required: false
          schema:
            type: string
            enum: [csv, xlsx]
            default: csv
      responses:
        '200': 
          description: Export file successfully
          content:
            text/csv:
              schema:
                type: string
                format: binary

  /users/me:
    get:
      tags:
        - Current user
      summary: Get current autheticated user
      operationId: getCurrentUser
      security:
        - bearerAuth: []
      responses:
        "200": 
          description: Current authenticated user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CurrentUser"
              example:
                - id: "user-001"
                  fullName: "Sophia Munn",
                  email: "sophia@untitled.com",
                  avatarUrl: "https://example.com/avatars/sophia.png"
                  role: "STORE_ADMIN",
                  storeId: "store-001"
        "401":
          description: User is not authenticated

      patch:
        tags:
          - Current id
        summary: Update current user profile
        operationId: updateCurrentUser
        security:
          - bearerAuth: []
        requestBody:
          required: true
          content: 
            application/json:
              schema:
                $ref: "#components/schemas/UpdateCurrentUserRequest"
        responses:
          "200":
            description: User profile updated successfully
            content: 
              application/json:
                schema:
                  $ref: "#/components/schemas/CurrentUser"
      
  /auth/logout:
    post:
      tags:
        - Authentication
      summary: Log out current user
      operationId: logout
      security:
       - bearerAuth: []
      responses:
        "204":
          description: Logged out successfully

        

components:

  # =========================================================
  # Parameters
  # =========================================================
  schemas:
    MetricsResponse:
      type: object
      properties:
        status:
          type: string
          example: success
        data:
          type: object
          properties:
            status:
              type: string
              example: sucess
            data: 
              type: object
              properties:
                total_customers:
                  $ref: "#/components/schemas/MetricDetail"
                members:
                  $ref: "#/components/schemas/MetricsDetail"
                active_now:
                  type: object
                  properties:
                    value:
                      type: integer
                      example: 316
                    recent_active_users:
                      type: array
                      items:
                        $ref: "#/components/schemas/UserAvatar"

    MetricDetail:
      type: object
      properties:
        value:
          type: integer
          example: 8486
        change_percentage:
          type: number
          format: float
          example: 20.0
        trend:
          type: string
          enum: [up,down]
          example: "up"
    
    UserAvatar:
      type: object
      properties:
        id: 
          type: string
          example: "usr_101"
        name:
          type: string
          example: "Sophia Munn"
        avatar_url:
          type: string
          example: "https://example.com/avatars/user1.jpa"

          # Customer list schemas
    
    CustomerListResponse:
      type: object
      properties:
        status: 
          type: string
          example: "success"
        data: 
          type: array
          items:
            $ref: "#/components/schemas/CustomerItem"
        pagination:
          $ref: "#/components/schemas/Pagination"
    
    CustomerItem:
      type: object
      properties:
        id: 
          type: string
          example: "cust_framer_01"
        company:
          type: object
          properties:
            name:
              type: string
              example: "Framer"
            domain:
              type: string
              example: "framer.com"
            logo_url:
              type: string
              example: "https://example.com/logos/framer.png"
            status:
              type: string
              enum: [Customer, Churned]
              example: "Customer"
            about:
              type: object
              properties: 
                category: 
                  type: string
                  example: "Design tool"
                description:
                  type: string
                  example: "Make beautiful websites in minutes."
            users:
              type: object
              properties:
                total_count:
                  type: integer
                  example: 9
                preview:
                  type: array
                  items: 
                    $ref: "#/compoents/schemas/UserAvatar"
                remaining_count:
                  type: integer
                  example: 4
    
    CreateCustomerRequest:
      type: object
      required:
        - company_name
        - domain
      properties:
        company_name: 
          type: string
          example: Framer
        domain:
          type: string
          example: "framer.com"
        category:
          type: string
          example: "Make beautiful websites in minutes"

    Pagination:
      type: object
      properties:
        current_page:
          type: integer
          example: 1
        per_page:
          type: integer
          example: 7
        total_records:
          type: integer
          example: 8486
        total_pages:
          type: integer
          example: 1210
        has_next:
          type: boolean
          example: true
        has_previous:
          type: boolean
          example: false
      
    CurrentUser:
      type: object
      required:
        - id 
        - fullname
        - email
        - role
      properties:
        id:
          type: string
          example: user-001
        fullName:
          type: string
          example: Sophia Munn
        email:
          type: string
          format: email
          example: sophia@untitled.com
        avatarUrl:
          type: string
          formar: uri
        role:
          type: string
          enum: 
            - STORE_OWNER
            - STORE_ADMIN
            - STORE_MEMBER
        storeId:
          type: string
          example: store-001
    
    UpdateCurrentUserRequest:
      type: object
      properties:
        fullName:
          type: string
          example: Sophia Munn
        
        avatarUrl:
          type: string
          format: uri
    
    securitySchemes:
      bearAuth:
        type: http
        scheme: bearer
        bearerFormat: JWT
            